pass_app/main/admin.py, pass_app/main/migrations/0002_auto_20150421_1635.py, pass_app/main/migrations/0003_auto_20150421_1643.py, pass_app/main/models.py, pass_app/main/templatetags/unlocked.py, pass_app/main/views.py
* also renaming the "user" field in UserVisited model to "profile". because it is a profile. not a user.
=> User profile fix for Django 1.7

pass_app/main/views.py
https://sentry.ccnmtl.columbia.edu/sentry-internal/pass/group/691/
`CareerLocationBlock.stakeholders` is a method.
=> :bug: instancemethod bugfix

pass_app/templates/pageblocks/imageblock_summary.html
* modify render summary to serve off of S3
=> Display ImageBlock on Edit Page

pass_app/supportservices/tests/factories.py, pass_app/supportservices/tests/test_models.py
=> Use Pagetree UserFactory

pass_app/templates/registration/login.html
Self-registered users were being redirected incorrectly to /accounts/profile/
* PMT# 101396
=> Fix self-registration login redirect

pass_app/careerlocation/migrations/0002_auto_20151021_1052.py, pass_app/careerlocation/models.py, pass_app/infographic/migrations/0002_auto_20151021_1052.py, pass_app/infographic/models.py, pass_app/specialneeds/migrations/0002_auto_20151021_1052.py, pass_app/specialneeds/models.py, pass_app/supportservices/migrations/0002_auto_20151021_1052.py, pass_app/supportservices/models.py, requirements.txt
* several "null has no effect on ManyToManyField"
* switch to django-registration-redux to resolve: RegistrationProfile.user: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
=> Fix warnings

pass_app/main/tests/test_views.py, pass_app/main/views.py, pass_app/mixins.py, pass_app/urls.py
circumvent production timeouts by going with StreamingHttpResponse
switch report view to cbv
=> Convert to StreamingHttpResponse

pass_app/templates/careerlocation/interview.html, pass_app/templates/careerlocation/strategy.html, pass_app/templates/careerlocation/strategy_js.html
* Remove activity headers - they are being duplicated
* Visual tweak for Download full proposal
=> Activity Polishing

pass_app/main/views.py
sentry error:
https://sentry.ccnmtl.columbia.edu/sentry-internal/pass/group/990/
=> Address list index error

pass_app/settings_shared.py, pass_app/templates/careerlocation/interview.html, pass_app/templates/careerlocation/strategy.html, pass_app/templates/careerlocation/summary.html, pass_app/templates/careermapblock/careermapblock.html, pass_app/templates/supportservices/list.html, requirements.txt
=> remove dependency on django-smartif

Makefile, pass_app/main/views.py
=> Complexity 7

pass_app/specialneeds/templatetags/phonecallstate.py
Check for the existence of user before accessing. This support the Hugo export operation.
=> Fix templatetag edge case

pass_app/main/management/commands/export_markdown.py, requirements.txt
* retrieve and stash image references into a static directory
* replace img & iframe video references with shortcodes
=> Image & Video postprocessing

pass_app/main/management/commands/export_markdown.py
Export specified pageblocks to a custom shortcode. Shortcodes stubbed out.
=> Map activities to shortcode

pass_app/main/management/commands/export_markdown.py
* by default, add a form to the section content
* by default, add a submit button on quiz pages
* export quizzes as "rhetorical"
=> Quiz export support

pass_app/main/management/commands/export_markdown.py
* only export forms if a Quiz is on the page
=> Export forms conditionally

pass_app/main/management/commands/export_markdown.py
If a section has no page blocks, do not generate a page
=> Ignore empty section pages

pass_app/templates/quizblock/question.html, pass_app/templates/quizblock/single_choice_prioritized.html
Pass does not use rhetorical quizzes. In order to facilitate the markdown export, update rhetorical quizzes to remove internal forms.
=> Update rhetorical quiz generation 

pass_app/main/management/commands/export_markdown.py
* exclude pages that are now part of a single-page javascript interactive
* remove recursive section walk in favor of pre-assembling an array of exportable sections. (this makes prev/next identification way cleaner)
=> Export interactives

pass_app/main/management/commands/export_markdown.py
=> careermap > careerplan

pass_app/main/management/commands/export_markdown.py
Map the existing video sources to new YouTube urls. (urls tbd)
=> Video export map

pass_app/main/management/commands/export_markdown.py
Small exporter shortcode change
=> Exporter refining interactive shortcodes

pass_app/main/management/commands/export_markdown.py
Turn on next behavior for the dentalcareerplan-pack interactive. See https://github.com/ccnmtl/dentalcareerplan-pack/pull/10 for more info.
=> Turn on "next" behavior
